services:
  webserver:
    build:
      context: dockerfiles
      dockerfile: Dockerfile.airflow
    command: webserver
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      PYTHONPATH: /opt/airflow:/opt/airflow/airflow_modules
      AIRFLOW_VAR_FROM_FILE: /opt/airflow/.env
      AIRFLOW__WEBSERVER__SECRET_KEY: "YourSuperSecretKeyHere"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./airflow_modules:/opt/airflow/airflow_modules  
      - ./dags:/opt/airflow/dags
      - ./requirements.txt:/opt/airflow/requirements.txt
      - ./.env:/opt/airflow/.env
    ports:
      - "8080:8080"
    entrypoint: >
      bash -c "
        set -e && \
        pip install --upgrade pip && \
        pip install -r /opt/airflow/requirements.txt && \
        /home/airflow/.local/bin/airflow db init && \
        /home/airflow/.local/bin/airflow users create --username admin --firstname admin --lastname admin --role Admin --email admin@example.com --password admin && \
        /home/airflow/.local/bin/airflow db migrate && \
        exec /home/airflow/.local/bin/airflow webserver
      "
    healthcheck:
      test: ['CMD-SHELL', "[ -f /opt/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - confluent

  scheduler:
    build:
      context: dockerfiles
      dockerfile: Dockerfile.airflow
    depends_on:
      webserver:
        condition: service_healthy
    volumes:
      - ./airflow_modules:/opt/airflow/airflow_modules  
      - ./dags:/opt/airflow/dags
      - ./requirements.txt:/opt/airflow/requirements.txt
      - ./.env:/opt/airflow/.env
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      PYTHONPATH: /opt/airflow:/opt/airflow/airflow_modules
      AIRFLOW__WEBSERVER__SECRET_KEY: "YourSuperSecretKeyHere"
    command: bash -c "pip install -r ./requirements.txt && airflow db migrate && airflow scheduler"
    networks:
      - confluent

  postgres:
    image: postgres:14.0
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
    - "5431:5432" 
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    logging:
      options:
        max-size: 10m
        max-file: "3"
    healthcheck:  
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - confluent

volumes:
  postgres-db-volume:

networks:
  confluent:
